name: InstallPyroscope
description: 'Installs Pyroscope'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: download pyroscope
      shell: bash
      run: | 
        curl -fL https://github.com/grafana/pyroscope/releases/download/v1.1.5/profilecli_1.1.5_linux_amd64.tar.gz | tar xz profilecli
        chmod +x profilecli
        sudo mv profilecli /usr/local/bin
    - name: create monitoring namespace
      shell: bash
      run: |
        kubectl create ns monitoring || true
        kubectl label ns monitoring scrape=enabled --overwrite=true
    - name: enable profiling
      shell: bash
      run: |
        kubectl annotate -n monitoring pods profiles.grafana.com/memory.scrape="true" -l app.kubernetes.io/name="karpenter"
        kubectl annotate -n monitoring pods profiles.grafana.com/memory.port="8000" -l app.kubernetes.io/name="karpenter"

        kubectl annotate -n monitoring pods profiles.grafana.com/cpu.scrape="true" -l app.kubernetes.io/name="karpenter"
        kubectl annotate -n monitoring pods profiles.grafana.com/cpu.port="8000" -l app.kubernetes.io/name="karpenter"

        kubectl annotate -n monitoring pods profiles.grafana.com/goroutine.scrape="true" -l app.kubernetes.io/name="karpenter"
        kubectl annotate -n monitoring pods profiles.grafana.com/goroutine.port="8000" -l app.kubernetes.io/name="karpenter"