# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group updates together, so that they are all applied in a single PR.
      # Grouped updates are currently in beta and is subject to change.
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      k8s-go-deps:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "knative.dev/*"
      go-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "knative.dev/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group updates together, so that they are all applied in a single PR.
      # Grouped updates are currently in beta and is subject to change.
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      actions-deps:
        patterns:
          - "*"
  # Everything under this line is currently auto-generated by hack/dependabot.sh
  # This needs to be generated since composite actions are currently not supported for auto-updates
  # through dependabot without explicitly setting their directory: https://github.com/dependabot/dependabot-core/issues/6704
  # If you need to make a change to this file, ensure that you make a change to hack/github/dependabot.sh first
  # That script assumes that the number of elements above this line is static and bases the append operation on it
  - package-ecosystem: github-actions
    directory: .github/actions/install-deps
    schedule:
      interval: weekly
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/install-prometheus
    schedule:
      interval: weekly
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/install-pyroscope
    schedule:
      interval: weekly
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/run-bench-test
    schedule:
      interval: weekly
    groups:
      action-deps:
        patterns:
          - '*'
