# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true
  timeout: 5m
  build-tags:
    - test_performance
linters:
  enable:
    - asciicheck
    - bidichk
    - errorlint
    - copyloopvar
    - gosec
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - gocyclo
    - govet
    - goimports
    - goheader
    - misspell
    - nilerr
  disable:
    - prealloc
linters-settings:
  gocyclo:
    min-complexity: 12
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: dot-imports
        disabled: true
  stylecheck:
    dot-import-whitelist:
      - "github.com/onsi/ginkgo/v2"
      - "github.com/onsi/gomega"
  misspell:
    locale: US
    ignore-words: []
  goimports:
    local-prefixes: sigs.k8s.io/karpenter
  goheader:
    template: |-
      Copyright The Kubernetes Authors.
      
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
    skip-generated: true
issues:
  fix: true
  exclude: ['declaration of "(err|ctx)" shadows declaration at']
  exclude-dirs:
    - tools
    - website
    - hack
    - charts
    - designs
  exclude-rules:
  - linters:
    - goheader
    path: 'zz_(.+)\.go'
  - linters:
    - goheader
    path: 'scheduling_benchmark_test.go'
