// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: SchedulingInput.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: will need to be updated as I continue to update SchedulingInput
// Anything as bytes are the self-describing wire format provided by K8s
type SchedulingInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PendingpodData    []*ReducedPod          `protobuf:"bytes,2,rep,name=pendingpod_data,json=pendingpodData,proto3" json:"pendingpod_data,omitempty"`
	StatenodesData    []*StateNodeWithPods   `protobuf:"bytes,3,rep,name=statenodes_data,json=statenodesData,proto3" json:"statenodes_data,omitempty"`
	InstancetypesData []*ReducedInstanceType `protobuf:"bytes,4,rep,name=instancetypes_data,json=instancetypesData,proto3" json:"instancetypes_data,omitempty"`
}

func (x *SchedulingInput) Reset() {
	*x = SchedulingInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingInput) ProtoMessage() {}

func (x *SchedulingInput) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingInput.ProtoReflect.Descriptor instead.
func (*SchedulingInput) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulingInput) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SchedulingInput) GetPendingpodData() []*ReducedPod {
	if x != nil {
		return x.PendingpodData
	}
	return nil
}

func (x *SchedulingInput) GetStatenodesData() []*StateNodeWithPods {
	if x != nil {
		return x.StatenodesData
	}
	return nil
}

func (x *SchedulingInput) GetInstancetypesData() []*ReducedInstanceType {
	if x != nil {
		return x.InstancetypesData
	}
	return nil
}

type ReducedPod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase     string `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
}

func (x *ReducedPod) Reset() {
	*x = ReducedPod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducedPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducedPod) ProtoMessage() {}

func (x *ReducedPod) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducedPod.ProtoReflect.Descriptor instead.
func (*ReducedPod) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{1}
}

func (x *ReducedPod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReducedPod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReducedPod) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type StateNodeWithPods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      *StateNodeWithPods_ReducedNode      `protobuf:"bytes,1,opt,name=node,proto3,oneof" json:"node,omitempty"`
	NodeClaim *StateNodeWithPods_ReducedNodeClaim `protobuf:"bytes,2,opt,name=nodeClaim,proto3,oneof" json:"nodeClaim,omitempty"` // might be problematic?
	Pods      []*ReducedPod                       `protobuf:"bytes,3,rep,name=pods,proto3" json:"pods,omitempty"`
}

func (x *StateNodeWithPods) Reset() {
	*x = StateNodeWithPods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateNodeWithPods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateNodeWithPods) ProtoMessage() {}

func (x *StateNodeWithPods) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateNodeWithPods.ProtoReflect.Descriptor instead.
func (*StateNodeWithPods) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{2}
}

func (x *StateNodeWithPods) GetNode() *StateNodeWithPods_ReducedNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *StateNodeWithPods) GetNodeClaim() *StateNodeWithPods_ReducedNodeClaim {
	if x != nil {
		return x.NodeClaim
	}
	return nil
}

func (x *StateNodeWithPods) GetPods() []*ReducedPod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type ReducedInstanceType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Requirements []*ReducedInstanceType_Requirement `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Offerings    []*ReducedInstanceType_Offering    `protobuf:"bytes,3,rep,name=offerings,proto3" json:"offerings,omitempty"`
}

func (x *ReducedInstanceType) Reset() {
	*x = ReducedInstanceType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducedInstanceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducedInstanceType) ProtoMessage() {}

func (x *ReducedInstanceType) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducedInstanceType.ProtoReflect.Descriptor instead.
func (*ReducedInstanceType) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{3}
}

func (x *ReducedInstanceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReducedInstanceType) GetRequirements() []*ReducedInstanceType_Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ReducedInstanceType) GetOfferings() []*ReducedInstanceType_Offering {
	if x != nil {
		return x.Offerings
	}
	return nil
}

type StateNodeWithPods_ReducedNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodestatus []byte `protobuf:"bytes,2,opt,name=nodestatus,proto3" json:"nodestatus,omitempty"`
}

func (x *StateNodeWithPods_ReducedNode) Reset() {
	*x = StateNodeWithPods_ReducedNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateNodeWithPods_ReducedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateNodeWithPods_ReducedNode) ProtoMessage() {}

func (x *StateNodeWithPods_ReducedNode) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateNodeWithPods_ReducedNode.ProtoReflect.Descriptor instead.
func (*StateNodeWithPods_ReducedNode) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{2, 0}
}

func (x *StateNodeWithPods_ReducedNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StateNodeWithPods_ReducedNode) GetNodestatus() []byte {
	if x != nil {
		return x.Nodestatus
	}
	return nil
}

type StateNodeWithPods_ReducedNodeClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StateNodeWithPods_ReducedNodeClaim) Reset() {
	*x = StateNodeWithPods_ReducedNodeClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateNodeWithPods_ReducedNodeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateNodeWithPods_ReducedNodeClaim) ProtoMessage() {}

func (x *StateNodeWithPods_ReducedNodeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateNodeWithPods_ReducedNodeClaim.ProtoReflect.Descriptor instead.
func (*StateNodeWithPods_ReducedNodeClaim) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{2, 1}
}

func (x *StateNodeWithPods_ReducedNodeClaim) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReducedInstanceType_Requirement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ReducedInstanceType_Requirement) Reset() {
	*x = ReducedInstanceType_Requirement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducedInstanceType_Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducedInstanceType_Requirement) ProtoMessage() {}

func (x *ReducedInstanceType_Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducedInstanceType_Requirement.ProtoReflect.Descriptor instead.
func (*ReducedInstanceType_Requirement) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ReducedInstanceType_Requirement) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ReducedInstanceType_Offering struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requirements []*ReducedInstanceType_Requirement `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Price        float64                            `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Available    bool                               `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *ReducedInstanceType_Offering) Reset() {
	*x = ReducedInstanceType_Offering{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SchedulingInput_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducedInstanceType_Offering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducedInstanceType_Offering) ProtoMessage() {}

func (x *ReducedInstanceType_Offering) ProtoReflect() protoreflect.Message {
	mi := &file_SchedulingInput_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducedInstanceType_Offering.ProtoReflect.Descriptor instead.
func (*ReducedInstanceType_Offering) Descriptor() ([]byte, []int) {
	return file_SchedulingInput_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ReducedInstanceType_Offering) GetRequirements() []*ReducedInstanceType_Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ReducedInstanceType_Offering) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ReducedInstanceType_Offering) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_SchedulingInput_proto protoreflect.FileDescriptor

var file_SchedulingInput_proto_rawDesc = []byte{
	0x0a, 0x15, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x72, 0x62, 0x22, 0xf3, 0x01, 0x0a,
	0x0f, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x38,
	0x0a, 0x0f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x64, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x64, 0x50, 0x6f, 0x64, 0x52, 0x0e, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x70, 0x6f, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3f, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x47, 0x0a, 0x12, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x11, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x54, 0x0a, 0x0a, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x50, 0x6f, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x22, 0xc3, 0x02, 0x0a, 0x11, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x50, 0x6f, 0x64, 0x73, 0x12, 0x3b,
	0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f,
	0x72, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x50, 0x6f, 0x64, 0x73, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x4a, 0x0a, 0x09, 0x6e,
	0x6f, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x50, 0x6f, 0x64, 0x73, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x48, 0x01, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x64, 0x50, 0x6f, 0x64, 0x52, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x1a, 0x41, 0x0a, 0x0b,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a,
	0x26, 0x0a, 0x10, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0xe6,
	0x02, 0x0a, 0x13, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x6f, 0x66, 0x66, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x25, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x88, 0x01, 0x0a,
	0x08, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x48, 0x0a, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x6f, 0x72, 0x62, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SchedulingInput_proto_rawDescOnce sync.Once
	file_SchedulingInput_proto_rawDescData = file_SchedulingInput_proto_rawDesc
)

func file_SchedulingInput_proto_rawDescGZIP() []byte {
	file_SchedulingInput_proto_rawDescOnce.Do(func() {
		file_SchedulingInput_proto_rawDescData = protoimpl.X.CompressGZIP(file_SchedulingInput_proto_rawDescData)
	})
	return file_SchedulingInput_proto_rawDescData
}

var file_SchedulingInput_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_SchedulingInput_proto_goTypes = []any{
	(*SchedulingInput)(nil),                    // 0: orb.SchedulingInput
	(*ReducedPod)(nil),                         // 1: orb.ReducedPod
	(*StateNodeWithPods)(nil),                  // 2: orb.StateNodeWithPods
	(*ReducedInstanceType)(nil),                // 3: orb.ReducedInstanceType
	(*StateNodeWithPods_ReducedNode)(nil),      // 4: orb.StateNodeWithPods.ReducedNode
	(*StateNodeWithPods_ReducedNodeClaim)(nil), // 5: orb.StateNodeWithPods.ReducedNodeClaim
	(*ReducedInstanceType_Requirement)(nil),    // 6: orb.ReducedInstanceType.Requirement
	(*ReducedInstanceType_Offering)(nil),       // 7: orb.ReducedInstanceType.Offering
}
var file_SchedulingInput_proto_depIdxs = []int32{
	1, // 0: orb.SchedulingInput.pendingpod_data:type_name -> orb.ReducedPod
	2, // 1: orb.SchedulingInput.statenodes_data:type_name -> orb.StateNodeWithPods
	3, // 2: orb.SchedulingInput.instancetypes_data:type_name -> orb.ReducedInstanceType
	4, // 3: orb.StateNodeWithPods.node:type_name -> orb.StateNodeWithPods.ReducedNode
	5, // 4: orb.StateNodeWithPods.nodeClaim:type_name -> orb.StateNodeWithPods.ReducedNodeClaim
	1, // 5: orb.StateNodeWithPods.pods:type_name -> orb.ReducedPod
	6, // 6: orb.ReducedInstanceType.requirements:type_name -> orb.ReducedInstanceType.Requirement
	7, // 7: orb.ReducedInstanceType.offerings:type_name -> orb.ReducedInstanceType.Offering
	6, // 8: orb.ReducedInstanceType.Offering.requirements:type_name -> orb.ReducedInstanceType.Requirement
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_SchedulingInput_proto_init() }
func file_SchedulingInput_proto_init() {
	if File_SchedulingInput_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SchedulingInput_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SchedulingInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReducedPod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StateNodeWithPods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReducedInstanceType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StateNodeWithPods_ReducedNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*StateNodeWithPods_ReducedNodeClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReducedInstanceType_Requirement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SchedulingInput_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReducedInstanceType_Offering); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_SchedulingInput_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SchedulingInput_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SchedulingInput_proto_goTypes,
		DependencyIndexes: file_SchedulingInput_proto_depIdxs,
		MessageInfos:      file_SchedulingInput_proto_msgTypes,
	}.Build()
	File_SchedulingInput_proto = out.File
	file_SchedulingInput_proto_rawDesc = nil
	file_SchedulingInput_proto_goTypes = nil
	file_SchedulingInput_proto_depIdxs = nil
}
