apiVersion: v1
kind: ConfigMap
metadata:
  name: dra-kwok-config
  namespace: karpenter
data:
  config.yaml: |
    driver: kwok.example.com/gpu
    mappings:
    - name: nvidia-gpu-mapping
      nodeSelector:
        matchLabels:
          node.kubernetes.io/instance-type: g4dn.xlarge
      resourceSlice:
        devices:
        - name: nvidia-gpu
          count: 1
          attributes:
            type: nvidia-tesla-v100
            memory: 32Gi
            cuda-cores: "5120"
    - name: nvidia-multi-gpu-mapping
      nodeSelector:
        matchLabels:
          node.kubernetes.io/instance-type: p3.8xlarge
      resourceSlice:
        devices:
        - name: nvidia-gpu
          count: 4
          attributes:
            type: nvidia-tesla-v100
            memory: 32Gi
            cuda-cores: "5120"
    - name: amd-gpu-mapping
      nodeSelector:
        matchLabels:
          node.kubernetes.io/instance-type: g4ad.xlarge
      resourceSlice:
        devices:
        - name: amd-gpu
          count: 1
          attributes:
            type: amd-radeon-pro-v520
            memory: 8Gi
            stream-processors: "2304"