//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package state

import (
	"github.com/aws/karpenter-core/pkg/apis/v1alpha5"
	"k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateNode) DeepCopyInto(out *StateNode) {
	*out = *in
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(v1.Node)
		(*in).DeepCopyInto(*out)
	}
	if in.Machine != nil {
		in, out := &in.Machine, &out.Machine
		*out = new(v1alpha5.Machine)
		(*in).DeepCopyInto(*out)
	}
	if in.inflightAllocatable != nil {
		in, out := &in.inflightAllocatable, &out.inflightAllocatable
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.inflightCapacity != nil {
		in, out := &in.inflightCapacity, &out.inflightCapacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.startupTaints != nil {
		in, out := &in.startupTaints, &out.startupTaints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.daemonSetRequests != nil {
		in, out := &in.daemonSetRequests, &out.daemonSetRequests
		*out = make(map[types.NamespacedName]v1.ResourceList, len(*in))
		for key, val := range *in {
			var outVal map[v1.ResourceName]resource.Quantity
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(v1.ResourceList, len(*in))
				for key, val := range *in {
					(*out)[key] = val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.daemonSetLimits != nil {
		in, out := &in.daemonSetLimits, &out.daemonSetLimits
		*out = make(map[types.NamespacedName]v1.ResourceList, len(*in))
		for key, val := range *in {
			var outVal map[v1.ResourceName]resource.Quantity
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(v1.ResourceList, len(*in))
				for key, val := range *in {
					(*out)[key] = val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.podRequests != nil {
		in, out := &in.podRequests, &out.podRequests
		*out = make(map[types.NamespacedName]v1.ResourceList, len(*in))
		for key, val := range *in {
			var outVal map[v1.ResourceName]resource.Quantity
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(v1.ResourceList, len(*in))
				for key, val := range *in {
					(*out)[key] = val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.podLimits != nil {
		in, out := &in.podLimits, &out.podLimits
		*out = make(map[types.NamespacedName]v1.ResourceList, len(*in))
		for key, val := range *in {
			var outVal map[v1.ResourceName]resource.Quantity
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(v1.ResourceList, len(*in))
				for key, val := range *in {
					(*out)[key] = val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.hostPortUsage != nil {
		in, out := &in.hostPortUsage, &out.hostPortUsage
		*out = (*in).DeepCopy()
	}
	if in.volumeUsage != nil {
		in, out := &in.volumeUsage, &out.volumeUsage
		*out = (*in).DeepCopy()
	}
	in.nominatedUntil.DeepCopyInto(&out.nominatedUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateNode.
func (in *StateNode) DeepCopy() *StateNode {
	if in == nil {
		return nil
	}
	out := new(StateNode)
	in.DeepCopyInto(out)
	return out
}
