// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: ORBLogEntry.proto

package orbbatcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sample entry, TODO: needs revisions
type ORBLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp      string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PendingpodData [][]byte `protobuf:"bytes,2,rep,name=pendingpod_data,json=pendingpodData,proto3" json:"pendingpod_data,omitempty"`
}

func (x *ORBLogEntry) Reset() {
	*x = ORBLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ORBLogEntry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ORBLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORBLogEntry) ProtoMessage() {}

func (x *ORBLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ORBLogEntry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORBLogEntry.ProtoReflect.Descriptor instead.
func (*ORBLogEntry) Descriptor() ([]byte, []int) {
	return file_ORBLogEntry_proto_rawDescGZIP(), []int{0}
}

func (x *ORBLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ORBLogEntry) GetPendingpodData() [][]byte {
	if x != nil {
		return x.PendingpodData
	}
	return nil
}

var File_ORBLogEntry_proto protoreflect.FileDescriptor

var file_ORBLogEntry_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4f, 0x52, 0x42, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x72, 0x62, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x22,
	0x54, 0x0a, 0x0b, 0x4f, 0x52, 0x42, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x27, 0x0a, 0x0f,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x6f,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ORBLogEntry_proto_rawDescOnce sync.Once
	file_ORBLogEntry_proto_rawDescData = file_ORBLogEntry_proto_rawDesc
)

func file_ORBLogEntry_proto_rawDescGZIP() []byte {
	file_ORBLogEntry_proto_rawDescOnce.Do(func() {
		file_ORBLogEntry_proto_rawDescData = protoimpl.X.CompressGZIP(file_ORBLogEntry_proto_rawDescData)
	})
	return file_ORBLogEntry_proto_rawDescData
}

var file_ORBLogEntry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ORBLogEntry_proto_goTypes = []any{
	(*ORBLogEntry)(nil), // 0: orbbatcher.ORBLogEntry
}
var file_ORBLogEntry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ORBLogEntry_proto_init() }
func file_ORBLogEntry_proto_init() {
	if File_ORBLogEntry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ORBLogEntry_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ORBLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ORBLogEntry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ORBLogEntry_proto_goTypes,
		DependencyIndexes: file_ORBLogEntry_proto_depIdxs,
		MessageInfos:      file_ORBLogEntry_proto_msgTypes,
	}.Build()
	File_ORBLogEntry_proto = out.File
	file_ORBLogEntry_proto_rawDesc = nil
	file_ORBLogEntry_proto_goTypes = nil
	file_ORBLogEntry_proto_depIdxs = nil
}
