name: kind-perf-e2e
on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, synchronize]
  workflow_run:
    workflows:
      - ApprovalComment
    types:
      - completed
  workflow_dispatch:
jobs:
  kind-perf-e2e:
    if: >-
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.labels.*.name, 'ok-to-test') &&
       !contains(github.event.pull_request.labels.*.name, 'skip-perf') &&
       (contains(github.event.pull_request.labels.*.name, 'perf-check') ||
        ((contains(github.event.pull_request.labels.*.name, 'size/XL') ||
          contains(github.event.pull_request.labels.*.name, 'size/XXL')) &&
         (startsWith(github.event.pull_request.title, 'feat:') ||
          startsWith(github.event.pull_request.title, 'fix:')))))
    permissions:
      issues: write
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: "Drift Performance"
            focus: "Drift Performance"
          - name: "Host Name Spreading"
            focus: "Host Name Spreading Deployment Reg"
          - name: "Host Name Spreading XL"
            focus: "Host Name Spreading Deployment XL"
          - name: "Wide Deployments"
            focus: "Wide Deployments"
          - name: "Basic Scale Test"
            focus: "Basic Deployment"
          - name: "Do Not Disrupt Performance"
            focus: "Do Not Disrupt Performance Test"
          - name: "Self Anti-Affinity Deployment Interference"
            focus: "Self Anti-Affinity Deployment Interference"
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Performance
      focus: ${{ matrix.test.focus }}
      test_name: ${{ matrix.test.name }}
      repeat: 10
