name: StaleBot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
permissions:
  contents: read
jobs:
  StaleBot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      discussions: write
      pull-requests: write
    if: github.repository == 'kubernetes-sigs/karpenter'
    name: Stale issue bot
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 14 days. StaleBot will close this stale issue after 14 more days of inactivity.'
          exempt-issue-labels: 'kind/cleanup,kind/testing,kind/documentation,kind/regression,kind/flake,kind/bug,kind/deprecation,kind/feature,kind/failing-test,kind/api-change,kind/automation'
          stale-issue-label: 'lifecycle/stale'
          close-issue-label: 'lifecycle/closed'
          stale-pr-message: 'This PR has been inactive for 14 days. StaleBot will close this stale PR after 14 more days of inactivity.'
          exempt-pr-labels: 'blocked,needs-review,needs-design'
          stale-pr-label: 'lifecycle/stale'
          close-pr-label: 'lifecycle/closed'
          days-before-stale: 14
          days-before-close: 14
          operations-per-run: 300
